name: 8 CNB ai merge
on:
  push: { branches: ["ai/**"] }
  workflow_dispatch:

jobs:
  call:
    uses: UpCNB/workflows/.github/workflows/cnb-ai-merge.yml@main
    with:
      upstream_repo: https://github.com/tale/headplane
      cnb_repo_url:  https://cnb.cool/g.h/headplane
      # fork_branch: main
      # push_fork_ff: true
      # open_pr_if_diverged: true
      # delete_ai_branch: false
    secrets: inherit
